import { parseThemeSettings } from '@snailicide/g-shopify-library'

import colors from './settings_colors.js'
import typography from './settings_typography.js'

const getSchema = () => {
    return parseThemeSettings([
        {
            name: 'theme_info',
            theme_author: 'Shopify',
            theme_documentation_url:
                'https://help.shopify.com/manual/online-store/themes',
            theme_name: 'Dawn',
            theme_support_url: 'https://support.shopify.com/',
            theme_version: '7.0.1',
        },
        colors,
        typography,
        {
            name: 't:settings_schema.layout.name',
            settings: [
                {
                    default: 1200,
                    id: 'page_width',
                    label: 't:settings_schema.layout.settings.page_width.label',
                    max: 1600,
                    min: 1000,
                    step: 100,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 0,
                    id: 'spacing_sections',
                    label: 't:settings_schema.layout.settings.spacing_sections.label',
                    max: 100,
                    min: 0,
                    step: 4,
                    type: 'range',
                    unit: 'px',
                },
                {
                    content:
                        't:settings_schema.layout.settings.header__grid.content',
                    type: 'header',
                },
                {
                    content:
                        't:settings_schema.layout.settings.paragraph__grid.content',
                    type: 'paragraph',
                },
                {
                    default: 8,
                    id: 'spacing_grid_horizontal',
                    label: 't:settings_schema.layout.settings.spacing_grid_horizontal.label',
                    max: 40,
                    min: 4,
                    step: 4,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 8,
                    id: 'spacing_grid_vertical',
                    label: 't:settings_schema.layout.settings.spacing_grid_vertical.label',
                    max: 40,
                    min: 4,
                    step: 4,
                    type: 'range',
                    unit: 'px',
                },
            ],
        },
        {
            name: 't:settings_schema.buttons.name',
            settings: [
                {
                    content:
                        't:settings_schema.global.settings.header__border.content',
                    type: 'header',
                },
                {
                    default: 1,
                    id: 'buttons_border_thickness',
                    label: 't:settings_schema.global.settings.thickness.label',
                    max: 12,
                    min: 0,
                    step: 1,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 100,
                    id: 'buttons_border_opacity',
                    label: 't:settings_schema.global.settings.opacity.label',
                    max: 100,
                    min: 0,
                    step: 5,
                    type: 'range',
                    unit: '%',
                },
                {
                    default: 0,
                    id: 'buttons_radius',
                    label: 't:settings_schema.global.settings.corner_radius.label',
                    max: 40,
                    min: 0,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    content:
                        't:settings_schema.global.settings.header__shadow.content',
                    type: 'header',
                },
                {
                    default: 0,
                    id: 'buttons_shadow_opacity',
                    label: 't:settings_schema.global.settings.opacity.label',
                    max: 100,
                    min: 0,
                    step: 5,
                    type: 'range',
                    unit: '%',
                },
                {
                    default: 0,
                    id: 'buttons_shadow_horizontal_offset',
                    label: 't:settings_schema.global.settings.horizontal_offset.label',
                    max: 12,
                    min: -12,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 0,
                    id: 'buttons_shadow_vertical_offset',
                    label: 't:settings_schema.global.settings.vertical_offset.label',
                    max: 12,
                    min: -12,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 0,
                    id: 'buttons_shadow_blur',
                    label: 't:settings_schema.global.settings.blur.label',
                    max: 20,
                    min: 0,
                    step: 5,
                    type: 'range',
                    unit: 'px',
                },
            ],
        },
        {
            name: 't:settings_schema.variant_pills.name',
            settings: [
                {
                    content: 't:settings_schema.variant_pills.paragraph',
                    type: 'paragraph',
                },
                {
                    content:
                        't:settings_schema.global.settings.header__border.content',
                    type: 'header',
                },
                {
                    default: 1,
                    id: 'variant_pills_border_thickness',
                    label: 't:settings_schema.global.settings.thickness.label',
                    max: 12,
                    min: 0,
                    step: 1,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 55,
                    id: 'variant_pills_border_opacity',
                    label: 't:settings_schema.global.settings.opacity.label',
                    max: 100,
                    min: 0,
                    step: 5,
                    type: 'range',
                    unit: '%',
                },
                {
                    default: 40,
                    id: 'variant_pills_radius',
                    label: 't:settings_schema.global.settings.corner_radius.label',
                    max: 40,
                    min: 0,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    content:
                        't:settings_schema.global.settings.header__shadow.content',
                    type: 'header',
                },
                {
                    default: 0,
                    id: 'variant_pills_shadow_opacity',
                    label: 't:settings_schema.global.settings.opacity.label',
                    max: 100,
                    min: 0,
                    step: 5,
                    type: 'range',
                    unit: '%',
                },
                {
                    default: 0,
                    id: 'variant_pills_shadow_horizontal_offset',
                    label: 't:settings_schema.global.settings.horizontal_offset.label',
                    max: 12,
                    min: -12,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 0,
                    id: 'variant_pills_shadow_vertical_offset',
                    label: 't:settings_schema.global.settings.vertical_offset.label',
                    max: 12,
                    min: -12,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 0,
                    id: 'variant_pills_shadow_blur',
                    label: 't:settings_schema.global.settings.blur.label',
                    max: 20,
                    min: 0,
                    step: 5,
                    type: 'range',
                    unit: 'px',
                },
            ],
        },
        {
            name: 't:settings_schema.inputs.name',
            settings: [
                {
                    content:
                        't:settings_schema.global.settings.header__border.content',
                    type: 'header',
                },
                {
                    default: 1,
                    id: 'inputs_border_thickness',
                    label: 't:settings_schema.global.settings.thickness.label',
                    max: 12,
                    min: 0,
                    step: 1,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 55,
                    id: 'inputs_border_opacity',
                    label: 't:settings_schema.global.settings.opacity.label',
                    max: 100,
                    min: 0,
                    step: 5,
                    type: 'range',
                    unit: '%',
                },
                {
                    default: 0,
                    id: 'inputs_radius',
                    label: 't:settings_schema.global.settings.corner_radius.label',
                    max: 40,
                    min: 0,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    content:
                        't:settings_schema.global.settings.header__shadow.content',
                    type: 'header',
                },
                {
                    default: 0,
                    id: 'inputs_shadow_opacity',
                    label: 't:settings_schema.global.settings.opacity.label',
                    max: 100,
                    min: 0,
                    step: 5,
                    type: 'range',
                    unit: '%',
                },
                {
                    default: 0,
                    id: 'inputs_shadow_horizontal_offset',
                    label: 't:settings_schema.global.settings.horizontal_offset.label',
                    max: 12,
                    min: -12,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 0,
                    id: 'inputs_shadow_vertical_offset',
                    label: 't:settings_schema.global.settings.vertical_offset.label',
                    max: 12,
                    min: -12,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 0,
                    id: 'inputs_shadow_blur',
                    label: 't:settings_schema.global.settings.blur.label',
                    max: 20,
                    min: 0,
                    step: 5,
                    type: 'range',
                    unit: 'px',
                },
            ],
        },
        {
            name: 't:settings_schema.cards.name',
            settings: [
                {
                    default: 'standard',
                    id: 'card_style',
                    label: 't:settings_schema.cards.settings.style.label',
                    options: [
                        {
                            label: 't:settings_schema.cards.settings.style.options__1.label',
                            value: 'standard',
                        },
                        {
                            label: 't:settings_schema.cards.settings.style.options__2.label',
                            value: 'card',
                        },
                    ],
                    type: 'select',
                },
                {
                    default: 0,
                    id: 'card_image_padding',
                    label: 't:settings_schema.global.settings.image_padding.label',
                    max: 20,
                    min: 0,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 'left',
                    id: 'card_text_alignment',
                    label: 't:settings_schema.global.settings.text_alignment.label',
                    options: [
                        {
                            label: 't:settings_schema.global.settings.text_alignment.options__1.label',
                            value: 'left',
                        },
                        {
                            label: 't:settings_schema.global.settings.text_alignment.options__2.label',
                            value: 'center',
                        },
                        {
                            label: 't:settings_schema.global.settings.text_alignment.options__3.label',
                            value: 'right',
                        },
                    ],
                    type: 'select',
                },
                {
                    default: 'background-2',
                    id: 'card_color_scheme',
                    label: 't:sections.all.colors.label',
                    options: [
                        {
                            label: 't:sections.all.colors.accent_1.label',
                            value: 'accent-1',
                        },
                        {
                            label: 't:sections.all.colors.accent_2.label',
                            value: 'accent-2',
                        },
                        {
                            label: 't:sections.all.colors.background_1.label',
                            value: 'background-1',
                        },
                        {
                            label: 't:sections.all.colors.background_2.label',
                            value: 'background-2',
                        },
                        {
                            label: 't:sections.all.colors.inverse.label',
                            value: 'inverse',
                        },
                    ],
                    type: 'select',
                },
                {
                    content:
                        't:settings_schema.global.settings.header__border.content',
                    type: 'header',
                },
                {
                    default: 0,
                    id: 'card_border_thickness',
                    label: 't:settings_schema.global.settings.thickness.label',
                    max: 24,
                    min: 0,
                    step: 1,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 0,
                    id: 'card_border_opacity',
                    label: 't:settings_schema.global.settings.opacity.label',
                    max: 100,
                    min: 0,
                    step: 5,
                    type: 'range',
                    unit: '%',
                },
                {
                    default: 0,
                    id: 'card_corner_radius',
                    label: 't:settings_schema.global.settings.corner_radius.label',
                    max: 40,
                    min: 0,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    content:
                        't:settings_schema.global.settings.header__shadow.content',
                    type: 'header',
                },
                {
                    default: 10,
                    id: 'card_shadow_opacity',
                    label: 't:settings_schema.global.settings.opacity.label',
                    max: 100,
                    min: 0,
                    step: 5,
                    type: 'range',
                    unit: '%',
                },
                {
                    default: 0,
                    id: 'card_shadow_horizontal_offset',
                    label: 't:settings_schema.global.settings.horizontal_offset.label',
                    max: 40,
                    min: -40,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 0,
                    id: 'card_shadow_vertical_offset',
                    label: 't:settings_schema.global.settings.vertical_offset.label',
                    max: 40,
                    min: -40,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 0,
                    id: 'card_shadow_blur',
                    label: 't:settings_schema.global.settings.blur.label',
                    max: 40,
                    min: 0,
                    step: 5,
                    type: 'range',
                    unit: 'px',
                },
            ],
        },
        {
            name: 't:settings_schema.collection_cards.name',
            settings: [
                {
                    default: 'standard',
                    id: 'collection_card_style',
                    label: 't:settings_schema.collection_cards.settings.style.label',
                    options: [
                        {
                            label: 't:settings_schema.collection_cards.settings.style.options__1.label',
                            value: 'standard',
                        },
                        {
                            label: 't:settings_schema.collection_cards.settings.style.options__2.label',
                            value: 'card',
                        },
                    ],
                    type: 'select',
                },
                {
                    default: 0,
                    id: 'collection_card_image_padding',
                    label: 't:settings_schema.global.settings.image_padding.label',
                    max: 20,
                    min: 0,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 'left',
                    id: 'collection_card_text_alignment',
                    label: 't:settings_schema.global.settings.text_alignment.label',
                    options: [
                        {
                            label: 't:settings_schema.global.settings.text_alignment.options__1.label',
                            value: 'left',
                        },
                        {
                            label: 't:settings_schema.global.settings.text_alignment.options__2.label',
                            value: 'center',
                        },
                        {
                            label: 't:settings_schema.global.settings.text_alignment.options__3.label',
                            value: 'right',
                        },
                    ],
                    type: 'select',
                },
                {
                    default: 'background-2',
                    id: 'collection_card_color_scheme',
                    label: 't:sections.all.colors.label',
                    options: [
                        {
                            label: 't:sections.all.colors.accent_1.label',
                            value: 'accent-1',
                        },
                        {
                            label: 't:sections.all.colors.accent_2.label',
                            value: 'accent-2',
                        },
                        {
                            label: 't:sections.all.colors.background_1.label',
                            value: 'background-1',
                        },
                        {
                            label: 't:sections.all.colors.background_2.label',
                            value: 'background-2',
                        },
                        {
                            label: 't:sections.all.colors.inverse.label',
                            value: 'inverse',
                        },
                    ],
                    type: 'select',
                },
                {
                    content:
                        't:settings_schema.global.settings.header__border.content',
                    type: 'header',
                },
                {
                    default: 0,
                    id: 'collection_card_border_thickness',
                    label: 't:settings_schema.global.settings.thickness.label',
                    max: 24,
                    min: 0,
                    step: 1,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 0,
                    id: 'collection_card_border_opacity',
                    label: 't:settings_schema.global.settings.opacity.label',
                    max: 100,
                    min: 0,
                    step: 5,
                    type: 'range',
                    unit: '%',
                },
                {
                    default: 0,
                    id: 'collection_card_corner_radius',
                    label: 't:settings_schema.global.settings.corner_radius.label',
                    max: 40,
                    min: 0,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    content:
                        't:settings_schema.global.settings.header__shadow.content',
                    type: 'header',
                },
                {
                    default: 10,
                    id: 'collection_card_shadow_opacity',
                    label: 't:settings_schema.global.settings.opacity.label',
                    max: 100,
                    min: 0,
                    step: 5,
                    type: 'range',
                    unit: '%',
                },
                {
                    default: 0,
                    id: 'collection_card_shadow_horizontal_offset',
                    label: 't:settings_schema.global.settings.horizontal_offset.label',
                    max: 40,
                    min: -40,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 0,
                    id: 'collection_card_shadow_vertical_offset',
                    label: 't:settings_schema.global.settings.vertical_offset.label',
                    max: 40,
                    min: -40,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 0,
                    id: 'collection_card_shadow_blur',
                    label: 't:settings_schema.global.settings.blur.label',
                    max: 40,
                    min: 0,
                    step: 5,
                    type: 'range',
                    unit: 'px',
                },
            ],
        },
        {
            name: 't:settings_schema.blog_cards.name',
            settings: [
                {
                    default: 'standard',
                    id: 'blog_card_style',
                    label: 't:settings_schema.blog_cards.settings.style.label',
                    options: [
                        {
                            label: 't:settings_schema.blog_cards.settings.style.options__1.label',
                            value: 'standard',
                        },
                        {
                            label: 't:settings_schema.blog_cards.settings.style.options__2.label',
                            value: 'card',
                        },
                    ],
                    type: 'select',
                },
                {
                    default: 0,
                    id: 'blog_card_image_padding',
                    label: 't:settings_schema.global.settings.image_padding.label',
                    max: 20,
                    min: 0,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 'left',
                    id: 'blog_card_text_alignment',
                    label: 't:settings_schema.global.settings.text_alignment.label',
                    options: [
                        {
                            label: 't:settings_schema.global.settings.text_alignment.options__1.label',
                            value: 'left',
                        },
                        {
                            label: 't:settings_schema.global.settings.text_alignment.options__2.label',
                            value: 'center',
                        },
                        {
                            label: 't:settings_schema.global.settings.text_alignment.options__3.label',
                            value: 'right',
                        },
                    ],
                    type: 'select',
                },
                {
                    default: 'background-2',
                    id: 'blog_card_color_scheme',
                    label: 't:sections.all.colors.label',
                    options: [
                        {
                            label: 't:sections.all.colors.accent_1.label',
                            value: 'accent-1',
                        },
                        {
                            label: 't:sections.all.colors.accent_2.label',
                            value: 'accent-2',
                        },
                        {
                            label: 't:sections.all.colors.background_1.label',
                            value: 'background-1',
                        },
                        {
                            label: 't:sections.all.colors.background_2.label',
                            value: 'background-2',
                        },
                        {
                            label: 't:sections.all.colors.inverse.label',
                            value: 'inverse',
                        },
                    ],
                    type: 'select',
                },
                {
                    content:
                        't:settings_schema.global.settings.header__border.content',
                    type: 'header',
                },
                {
                    default: 0,
                    id: 'blog_card_border_thickness',
                    label: 't:settings_schema.global.settings.thickness.label',
                    max: 24,
                    min: 0,
                    step: 1,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 0,
                    id: 'blog_card_border_opacity',
                    label: 't:settings_schema.global.settings.opacity.label',
                    max: 100,
                    min: 0,
                    step: 5,
                    type: 'range',
                    unit: '%',
                },
                {
                    default: 0,
                    id: 'blog_card_corner_radius',
                    label: 't:settings_schema.global.settings.corner_radius.label',
                    max: 40,
                    min: 0,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    content:
                        't:settings_schema.global.settings.header__shadow.content',
                    type: 'header',
                },
                {
                    default: 10,
                    id: 'blog_card_shadow_opacity',
                    label: 't:settings_schema.global.settings.opacity.label',
                    max: 100,
                    min: 0,
                    step: 5,
                    type: 'range',
                    unit: '%',
                },
                {
                    default: 0,
                    id: 'blog_card_shadow_horizontal_offset',
                    label: 't:settings_schema.global.settings.horizontal_offset.label',
                    max: 40,
                    min: -40,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 0,
                    id: 'blog_card_shadow_vertical_offset',
                    label: 't:settings_schema.global.settings.vertical_offset.label',
                    max: 40,
                    min: -40,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 0,
                    id: 'blog_card_shadow_blur',
                    label: 't:settings_schema.global.settings.blur.label',
                    max: 40,
                    min: 0,
                    step: 5,
                    type: 'range',
                    unit: 'px',
                },
            ],
        },
        {
            name: 't:settings_schema.content_containers.name',
            settings: [
                {
                    content:
                        't:settings_schema.global.settings.header__border.content',
                    type: 'header',
                },
                {
                    default: 0,
                    id: 'text_boxes_border_thickness',
                    label: 't:settings_schema.global.settings.thickness.label',
                    max: 24,
                    min: 0,
                    step: 1,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 0,
                    id: 'text_boxes_border_opacity',
                    label: 't:settings_schema.global.settings.opacity.label',
                    max: 100,
                    min: 0,
                    step: 5,
                    type: 'range',
                    unit: '%',
                },
                {
                    default: 0,
                    id: 'text_boxes_radius',
                    label: 't:settings_schema.global.settings.corner_radius.label',
                    max: 40,
                    min: 0,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    content:
                        't:settings_schema.global.settings.header__shadow.content',
                    type: 'header',
                },
                {
                    default: 0,
                    id: 'text_boxes_shadow_opacity',
                    label: 't:settings_schema.global.settings.opacity.label',
                    max: 100,
                    min: 0,
                    step: 5,
                    type: 'range',
                    unit: '%',
                },
                {
                    default: 0,
                    id: 'text_boxes_shadow_horizontal_offset',
                    label: 't:settings_schema.global.settings.horizontal_offset.label',
                    max: 40,
                    min: -40,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 0,
                    id: 'text_boxes_shadow_vertical_offset',
                    label: 't:settings_schema.global.settings.vertical_offset.label',
                    max: 40,
                    min: -40,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 0,
                    id: 'text_boxes_shadow_blur',
                    label: 't:settings_schema.global.settings.blur.label',
                    max: 40,
                    min: 0,
                    step: 5,
                    type: 'range',
                    unit: 'px',
                },
            ],
        },
        {
            name: 't:settings_schema.media.name',
            settings: [
                {
                    content:
                        't:settings_schema.global.settings.header__border.content',
                    type: 'header',
                },
                {
                    default: 1,
                    id: 'media_border_thickness',
                    label: 't:settings_schema.global.settings.thickness.label',
                    max: 24,
                    min: 0,
                    step: 1,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 5,
                    id: 'media_border_opacity',
                    label: 't:settings_schema.global.settings.opacity.label',
                    max: 100,
                    min: 0,
                    step: 5,
                    type: 'range',
                    unit: '%',
                },
                {
                    default: 0,
                    id: 'media_radius',
                    label: 't:settings_schema.global.settings.corner_radius.label',
                    max: 40,
                    min: 0,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    content:
                        't:settings_schema.global.settings.header__shadow.content',
                    type: 'header',
                },
                {
                    default: 0,
                    id: 'media_shadow_opacity',
                    label: 't:settings_schema.global.settings.opacity.label',
                    max: 100,
                    min: 0,
                    step: 5,
                    type: 'range',
                    unit: '%',
                },
                {
                    default: 0,
                    id: 'media_shadow_horizontal_offset',
                    label: 't:settings_schema.global.settings.horizontal_offset.label',
                    max: 40,
                    min: -40,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 0,
                    id: 'media_shadow_vertical_offset',
                    label: 't:settings_schema.global.settings.vertical_offset.label',
                    max: 40,
                    min: -40,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 0,
                    id: 'media_shadow_blur',
                    label: 't:settings_schema.global.settings.blur.label',
                    max: 40,
                    min: 0,
                    step: 5,
                    type: 'range',
                    unit: 'px',
                },
            ],
        },
        {
            name: 't:settings_schema.popups.name',
            settings: [
                {
                    content: 't:settings_schema.popups.paragraph',
                    type: 'paragraph',
                },
                {
                    content:
                        't:settings_schema.global.settings.header__border.content',
                    type: 'header',
                },
                {
                    default: 1,
                    id: 'popup_border_thickness',
                    label: 't:settings_schema.global.settings.thickness.label',
                    max: 24,
                    min: 0,
                    step: 1,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 10,
                    id: 'popup_border_opacity',
                    label: 't:settings_schema.global.settings.opacity.label',
                    max: 100,
                    min: 0,
                    step: 5,
                    type: 'range',
                    unit: '%',
                },
                {
                    default: 0,
                    id: 'popup_corner_radius',
                    label: 't:settings_schema.global.settings.corner_radius.label',
                    max: 40,
                    min: 0,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    content:
                        't:settings_schema.global.settings.header__shadow.content',
                    type: 'header',
                },
                {
                    default: 0,
                    id: 'popup_shadow_opacity',
                    label: 't:settings_schema.global.settings.opacity.label',
                    max: 100,
                    min: 0,
                    step: 5,
                    type: 'range',
                    unit: '%',
                },
                {
                    default: 0,
                    id: 'popup_shadow_horizontal_offset',
                    label: 't:settings_schema.global.settings.horizontal_offset.label',
                    max: 40,
                    min: -40,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 0,
                    id: 'popup_shadow_vertical_offset',
                    label: 't:settings_schema.global.settings.vertical_offset.label',
                    max: 40,
                    min: -40,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 0,
                    id: 'popup_shadow_blur',
                    label: 't:settings_schema.global.settings.blur.label',
                    max: 40,
                    min: 0,
                    step: 5,
                    type: 'range',
                    unit: 'px',
                },
            ],
        },
        {
            name: 't:settings_schema.drawers.name',
            settings: [
                {
                    content:
                        't:settings_schema.global.settings.header__border.content',
                    type: 'header',
                },
                {
                    default: 1,
                    id: 'drawer_border_thickness',
                    label: 't:settings_schema.global.settings.thickness.label',
                    max: 24,
                    min: 0,
                    step: 1,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 10,
                    id: 'drawer_border_opacity',
                    label: 't:settings_schema.global.settings.opacity.label',
                    max: 100,
                    min: 0,
                    step: 5,
                    type: 'range',
                    unit: '%',
                },
                {
                    content:
                        't:settings_schema.global.settings.header__shadow.content',
                    type: 'header',
                },
                {
                    default: 0,
                    id: 'drawer_shadow_opacity',
                    label: 't:settings_schema.global.settings.opacity.label',
                    max: 100,
                    min: 0,
                    step: 5,
                    type: 'range',
                    unit: '%',
                },
                {
                    default: 0,
                    id: 'drawer_shadow_horizontal_offset',
                    label: 't:settings_schema.global.settings.horizontal_offset.label',
                    max: 40,
                    min: -40,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 0,
                    id: 'drawer_shadow_vertical_offset',
                    label: 't:settings_schema.global.settings.vertical_offset.label',
                    max: 40,
                    min: -40,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 0,
                    id: 'drawer_shadow_blur',
                    label: 't:settings_schema.global.settings.blur.label',
                    max: 40,
                    min: 0,
                    step: 5,
                    type: 'range',
                    unit: 'px',
                },
            ],
        },
        {
            name: 't:settings_schema.badges.name',
            settings: [
                {
                    default: 'bottom left',
                    id: 'badge_position',
                    label: 't:settings_schema.badges.settings.position.label',
                    options: [
                        {
                            label: 't:settings_schema.badges.settings.position.options__1.label',
                            value: 'bottom left',
                        },
                        {
                            label: 't:settings_schema.badges.settings.position.options__2.label',
                            value: 'bottom right',
                        },
                        {
                            label: 't:settings_schema.badges.settings.position.options__3.label',
                            value: 'top left',
                        },
                        {
                            label: 't:settings_schema.badges.settings.position.options__4.label',
                            value: 'top right',
                        },
                    ],
                    type: 'select',
                },
                {
                    default: 40,
                    id: 'badge_corner_radius',
                    label: 't:settings_schema.global.settings.corner_radius.label',
                    max: 40,
                    min: 0,
                    step: 2,
                    type: 'range',
                    unit: 'px',
                },
                {
                    default: 'accent-2',
                    id: 'sale_badge_color_scheme',
                    label: 't:settings_schema.badges.settings.sale_badge_color_scheme.label',
                    options: [
                        {
                            label: 't:sections.all.colors.accent_1.label',
                            value: 'accent-1',
                        },
                        {
                            label: 't:sections.all.colors.accent_2.label',
                            value: 'accent-2',
                        },
                        {
                            label: 't:sections.all.colors.background_2.label',
                            value: 'background-2',
                        },
                    ],
                    type: 'select',
                },
                {
                    default: 'inverse',
                    id: 'sold_out_badge_color_scheme',
                    label: 't:settings_schema.badges.settings.sold_out_badge_color_scheme.label',
                    options: [
                        {
                            label: 't:sections.all.colors.background_1.label',
                            value: 'background-1',
                        },
                        {
                            label: 't:sections.all.colors.inverse.label',
                            value: 'inverse',
                        },
                    ],
                    type: 'select',
                },
            ],
        },
        {
            name: 't:settings_schema.styles.name',
            settings: [
                {
                    default: 'text',
                    id: 'accent_icons',
                    label: 't:settings_schema.styles.settings.accent_icons.label',
                    options: [
                        {
                            label: 't:sections.all.colors.accent_1.label',
                            value: 'accent-1',
                        },
                        {
                            label: 't:sections.all.colors.accent_2.label',
                            value: 'accent-2',
                        },
                        {
                            label: 't:settings_schema.styles.settings.accent_icons.options__3.label',
                            value: 'outline-button',
                        },
                        {
                            label: 't:settings_schema.styles.settings.accent_icons.options__4.label',
                            value: 'text',
                        },
                    ],
                    type: 'select',
                },
            ],
        },
        {
            name: 't:settings_schema.social-media.name',
            settings: [
                {
                    content:
                        't:settings_schema.social-media.settings.header.content',
                    type: 'header',
                },
                {
                    id: 'social_twitter_link',
                    info: 't:settings_schema.social-media.settings.social_twitter_link.info',
                    label: 't:settings_schema.social-media.settings.social_twitter_link.label',
                    type: 'text',
                },
                {
                    id: 'social_facebook_link',
                    info: 't:settings_schema.social-media.settings.social_facebook_link.info',
                    label: 't:settings_schema.social-media.settings.social_facebook_link.label',
                    type: 'text',
                },
                {
                    id: 'social_pinterest_link',
                    info: 't:settings_schema.social-media.settings.social_pinterest_link.info',
                    label: 't:settings_schema.social-media.settings.social_pinterest_link.label',
                    type: 'text',
                },
                {
                    id: 'social_instagram_link',
                    info: 't:settings_schema.social-media.settings.social_instagram_link.info',
                    label: 't:settings_schema.social-media.settings.social_instagram_link.label',
                    type: 'text',
                },
                {
                    id: 'social_tiktok_link',
                    info: 't:settings_schema.social-media.settings.social_tiktok_link.info',
                    label: 't:settings_schema.social-media.settings.social_tiktok_link.label',
                    type: 'text',
                },
                {
                    id: 'social_tumblr_link',
                    info: 't:settings_schema.social-media.settings.social_tumblr_link.info',
                    label: 't:settings_schema.social-media.settings.social_tumblr_link.label',
                    type: 'text',
                },
                {
                    id: 'social_snapchat_link',
                    info: 't:settings_schema.social-media.settings.social_snapchat_link.info',
                    label: 't:settings_schema.social-media.settings.social_snapchat_link.label',
                    type: 'text',
                },
                {
                    id: 'social_youtube_link',
                    info: 't:settings_schema.social-media.settings.social_youtube_link.info',
                    label: 't:settings_schema.social-media.settings.social_youtube_link.label',
                    type: 'text',
                },
                {
                    id: 'social_vimeo_link',
                    info: 't:settings_schema.social-media.settings.social_vimeo_link.info',
                    label: 't:settings_schema.social-media.settings.social_vimeo_link.label',
                    type: 'text',
                },
            ],
        },
        {
            name: 't:settings_schema.search_input.name',
            settings: [
                {
                    content:
                        't:settings_schema.search_input.settings.header.content',
                    type: 'header',
                },
                {
                    default: true,
                    id: 'predictive_search_enabled',
                    label: 't:settings_schema.search_input.settings.predictive_search_enabled.label',
                    type: 'checkbox',
                },
                {
                    default: false,
                    id: 'predictive_search_show_vendor',
                    info: 't:settings_schema.search_input.settings.predictive_search_show_vendor.info',
                    label: 't:settings_schema.search_input.settings.predictive_search_show_vendor.label',
                    type: 'checkbox',
                },
                {
                    default: false,
                    id: 'predictive_search_show_price',
                    info: 't:settings_schema.search_input.settings.predictive_search_show_price.info',
                    label: 't:settings_schema.search_input.settings.predictive_search_show_price.label',
                    type: 'checkbox',
                },
            ],
        },
        {
            name: 't:settings_schema.favicon.name',
            settings: [
                {
                    id: 'favicon',
                    info: 't:settings_schema.favicon.settings.favicon.info',
                    label: 't:settings_schema.favicon.settings.favicon.label',
                    type: 'image_picker',
                },
            ],
        },
        {
            name: 't:settings_schema.currency_format.name',
            settings: [
                {
                    content:
                        't:settings_schema.currency_format.settings.content',
                    type: 'header',
                },
                {
                    content:
                        't:settings_schema.currency_format.settings.paragraph',
                    type: 'paragraph',
                },
                {
                    default: true,
                    id: 'currency_code_enabled',
                    label: 't:settings_schema.currency_format.settings.currency_code_enabled.label',
                    type: 'checkbox',
                },
            ],
        },
        {
            name: 't:settings_schema.cart.name',
            settings: [
                {
                    default: 'notification',
                    id: 'cart_type',
                    label: 't:settings_schema.cart.settings.cart_type.label',
                    options: [
                        {
                            label: 't:settings_schema.cart.settings.cart_type.drawer.label',
                            value: 'drawer',
                        },
                        {
                            label: 't:settings_schema.cart.settings.cart_type.page.label',
                            value: 'page',
                        },
                        {
                            label: 't:settings_schema.cart.settings.cart_type.notification.label',
                            value: 'notification',
                        },
                    ],
                    type: 'select',
                },
                {
                    default: false,
                    id: 'show_vendor',
                    label: 't:settings_schema.cart.settings.show_vendor.label',
                    type: 'checkbox',
                },
                {
                    default: false,
                    id: 'show_cart_note',
                    label: 't:settings_schema.cart.settings.show_cart_note.label',
                    type: 'checkbox',
                },
                {
                    content:
                        't:settings_schema.cart.settings.cart_drawer.header',
                    type: 'header',
                },
                {
                    id: 'cart_drawer_collection',
                    info: 't:settings_schema.cart.settings.cart_drawer.collection.info',
                    label: 't:settings_schema.cart.settings.cart_drawer.collection.label',
                    type: 'collection',
                },
            ],
        },
    ])
}
export default getSchema()
