name: snailicide/build
on:
  workflow_call:
    inputs:
      PACKAGE_NAME:
        required: true
        type: string
jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:

      - name: Build Snailicide Monorepo 🐌

      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Node.js environment 🛎️
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '18.7.0'

      - name: Install pnpm 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install -g pnpm
          pnpm install

      - name: BUILD ALL PACKAGES
        run: |
          pnpm run build && pnpm run fix && pnpm run check
