name: Snailicide Release Wrapper
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
permissions:
  contents: write
jobs:
  test-g-library:
    uses: ./workflows/workflow-release-package.yml
    with:
      PACKAGE_NAME: '@snailicide/g-library'
