import tg_json from './json.typeguards.js'
import { isZodParsable } from './../zod_helpers/index.js'
import { isCSSColorSpecial, isNotCSSColorSpecial } from './../browser/css.js'
import { isNPMPackage } from './../npm/npm.package.js'
import {
    isFalsy,
    isTruthy,
    isNilOrEmpty,
    isNotNilOrEmpty,
    isEmptyString,
    isNotString,
    isString,
    isEmptyArray,
    isArray,
    isNonEmptyArray,
    isPlainObject,
    isNotNull,
    isNull,
    isNotPrimitive,
    isInteger,
    isPrimitive,
    isNotInteger,
    isEmptyObject,
    isNonEmptyObject,
    isNilLike,
    isNotNilLike,
    isNotNullish,
    isNullish,
    isNotUndefined,
    isUndefined,
    isMatchRegExp,
} from './utility.typeguards.js'

export const tg = {
    isFalsy,
    isTruthy,
    isNilOrEmpty,
    isNotNilOrEmpty,
    isEmptyString,
    isNotString,
    isString,
    isEmptyArray,
    isArray,
    isNonEmptyArray,
    isPlainObject,
    isNotNull,
    isNull,
    isNotPrimitive,
    isInteger,
    isPrimitive,
    isNotInteger,
    isEmptyObject,
    isNonEmptyObject,
    isNilLike,
    isNotNilLike,
    isNotNullish,
    isNullish,
    isNotUndefined,
    isUndefined,
    isMatchRegExp,
    ...tg_json,
    isZodParsable,
    isCSSColorSpecial,
    isNotCSSColorSpecial,
    isNPMPackage,
}
export default tg
