import {
    isFalsy,
    isTruthy,
    isNilOrEmpty,
    isNotNilOrEmpty,
    isEmptyString,
    isNotString,
    isString,
    isEmptyArray,
    isArray,
    isNonEmptyArray,
    isPlainObject,
    isNotNull,
    isNull,
    isNotPrimitive,
    isInteger,
    isPrimitive,
    isNotInteger,
    isEmptyObject,
    isNonEmptyObject,
    isNilLike,
    isNotNilLike,
    isNotNullish,
    isNullish,
    isNotUndefined,
    isUndefined,
    isValidRegExp,
} from './utility.typeguards.js'

export const tg = {
    isFalsy,
    isTruthy,
    isNilOrEmpty,
    isNotNilOrEmpty,
    isEmptyString,
    isNotString,
    isString,
    isEmptyArray,
    isArray,
    isNonEmptyArray,
    isPlainObject,
    isNotNull,
    isNull,
    isNotPrimitive,
    isInteger,
    isPrimitive,
    isNotInteger,
    isEmptyObject,
    isNonEmptyObject,
    isNilLike,
    isNotNilLike,
    isNotNullish,
    isNullish,
    isNotUndefined,
    isUndefined,
    isValidRegExp,
}
export default tg
