import tg_json from './json.typeguards.js'
import { isZodParsable } from './../zod_helpers/index.js'
import { isCSSColorSpecial, isNotCSSColorSpecial } from './../browser/css.js'
import {
    isNumeric,
    isNumericFloat,
    isNumericInteger,
} from './../number/numeric.js'

import {
    isFalsy,
    isTruthy,
    isNilOrEmpty,
    isNotNilOrEmpty,
    isEmptyString,
    isNotString,
    isString,
    isEmptyArray,
    isArray,
    isNonEmptyArray,
    isPlainObject,
    isNotNull,
    isNull,
    isNotPrimitive,
    isInteger,
    isPrimitive,
    isNotInteger,
    isEmptyObject,
    isNonEmptyObject,
    isNilLike,
    isNotNilLike,
    isNotNullish,
    isNullish,
    isNotUndefined,
    isUndefined,
    isError,
    isNotError,
    isRegExp,
    isBigInt,
} from './utility.typeguards.js'

export const tg = {
    isFalsy,
    isTruthy,
    isNilOrEmpty,
    isNotNilOrEmpty,
    isEmptyString,
    isNotString,
    isString,
    isEmptyArray,
    isArray,
    isNonEmptyArray,
    isPlainObject,
    isNotNull,
    isNull,
    isNotPrimitive,
    isInteger,
    isPrimitive,
    isNotInteger,
    isEmptyObject,
    isNonEmptyObject,
    isNilLike,
    isNotNilLike,
    isNotNullish,
    isNullish,
    isNotUndefined,
    isUndefined,
    isError,
    isNotError,
    isRegExp,
    isBigInt,
    ...tg_json,
    isZodParsable,
    isCSSColorSpecial,
    isNotCSSColorSpecial,
    isNumeric,
    isNumericInteger,
    isNumericFloat,
}
export default tg
