import {
    isFalsy,
    isTruthy,
    isNilOrEmpty,
    isNotNil,
    isNotArray,
    isNotNilOrEmpty,
    isEmptyString,
    isNotString,
    isInteger,
    isNotInteger,
    isPrimitive,
    isNotPrimitive,
    isString,
    isNull,
    isNotNull,
    isNonEmptyArray,
    isPlainObject,
    isArray,
    isEmptyArray,
} from 'ramda-adjunct'
export const RA = {
    isFalsy,
    isTruthy,
    isNilOrEmpty,
    isNotNil,
    isNotArray,
    isNotNilOrEmpty,
    isEmptyString,
    isNotString,

    isString,
    isNull,
    isNotNull,
    isNonEmptyArray,
    isPlainObject,
    isArray,
    isEmptyArray,

    isInteger,
    isNotInteger,
    isPrimitive,
    isNotPrimitive,
}
