#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

pnpm exec git-branch-is  -i -r "^feat/"

# pnpm exec commitlint --edit "$1"

if $
then
       echo "branch check: failed, aborting commit."
else
  # branch passes, then commitlint.
   echo "branch check: success, continueing to commit lint"
  pnpm exec commitlint --edit "$1"
   echo "commitlint success"
fi
