#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

pnpm exec git-branch-is  -i -r "^feat/"

# pnpm exec commitlint --edit "$1"

if $
then
        echo "Both variables are the same"
else
        echo "Both variables are different"
fi
